### ISSUE TITLE
GraphQL API

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/typehead-server#3]

**Comment by 0pdd** [comment]
@h1alexbel 5 puzzles [#25](https://github.com/h1alexbel/typehead-server/issues/25), [#26](https://github.com/h1alexbel/typehead-server/issues/26), [#27](https://github.com/h1alexbel/typehead-server/issues/27), [#28](https://github.com/h1alexbel/typehead-server/issues/28), [#29](https://github.com/h1alexbel/typehead-server/issues/29) are still not solved.
